# Generated by Django 3.2.16 on 2024-01-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCode', models.CharField(max_length=200)),
                ('customerCode', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookCode', models.CharField(max_length=200)),
                ('customerCode', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('dateOrd', models.DateField(null=True)),
            ],
        ),
    ]
